import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Entirely autogenerated from the docs/ tree. tools/split_spec.py writes a
// sidebar_position onto every page and a _category_.json onto every section,
// both taken from where the thing sits in the specification -- so the sidebar
// is the document's own order and stays that way when a rule is added.
//
// This file used to list the narrative pages by hand, and had silently lost
// two of them: `scope` and `what-changed-in-v2` were published but unreachable.
// Nothing is named here now, so nothing can be left out.
const sidebars: SidebarsConfig = {
  spec: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
